// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAicoh7pMdTeCJGHDSrIddLNVuhIjOec7M',
    appId: '1:992832430048:web:0e10bb5076a0ef06e35585',
    messagingSenderId: '992832430048',
    projectId: 'newsapp-dc95c',
    authDomain: 'newsapp-dc95c.firebaseapp.com',
    storageBucket: 'newsapp-dc95c.appspot.com',
    measurementId: 'G-2NG720TX7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWoe_ftp7xn9phAo3PIr5w__SZ9ygmEAA',
    appId: '1:992832430048:android:cd6e78e014da3094e35585',
    messagingSenderId: '992832430048',
    projectId: 'newsapp-dc95c',
    storageBucket: 'newsapp-dc95c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDQnhAVpaqdTKvpaHwmgiA84ytNGKWY5Y',
    appId: '1:992832430048:ios:d9bb67bfa222d564e35585',
    messagingSenderId: '992832430048',
    projectId: 'newsapp-dc95c',
    storageBucket: 'newsapp-dc95c.appspot.com',
    iosClientId: '992832430048-krpaqb2rclah252oq7tvrso2cj06on66.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDQnhAVpaqdTKvpaHwmgiA84ytNGKWY5Y',
    appId: '1:992832430048:ios:f58769ca598f6d58e35585',
    messagingSenderId: '992832430048',
    projectId: 'newsapp-dc95c',
    storageBucket: 'newsapp-dc95c.appspot.com',
    iosClientId: '992832430048-k1e2ju1dr5caq2gmdsjpe4gmr9jip1ru.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
